In [1]:
import numpy as np

In [2]:
name = np.array(['Adil', 'Ali', 'Erdum', 'Ahmed'])

In [3]:
print(name)

['Adil' 'Ali' 'Erdum' 'Ahmed']


In [4]:
print(name.dtype)

<U5


In [5]:
strg = np.array(["2","3","5","8"])

In [6]:
print(strg)

['2' '3' '5' '8']


In [7]:
print(strg.dtype)

<U1


In [8]:
num = np.array([1,2,3,4])
print(num)

[1 2 3 4]


In [9]:
num = np.array([1,2,3,4], dtype='i')

In [10]:
print(num.dtype)

int32


In [11]:
flt = np.array([1.2,2.6,3.5,6.8], dtype='f')
print(flt.dtype)

float32


In [12]:
# Transforming float data type into interger data type

In [13]:
flt = np.array([1.2,2.6,3.5,6.8,0,-3], dtype='i')
print(flt.dtype)

int32


In [14]:
print(flt)

[ 1  2  3  6  0 -3]


In [31]:
flt_1 = flt.astype(float)
print(flt_1)

[ 1.  2.  3.  6.  0. -3.]


In [32]:
boolean = flt_1.astype(bool)
print(boolean)

[ True  True  True  True False  True]


In [33]:
num = np.array([1,2,3,4], dtype='i')

In [34]:
v = num.view()
print(v)

[1 2 3 4]


In [35]:
v[0] = 10
print(num)

[10  2  3  4]


In [36]:
c = v.copy()
print(v)
print(num)

[10  2  3  4]
[10  2  3  4]


In [37]:
print(c.base)
print(v.base)
print(num.base)

None
[10  2  3  4]
None


In [38]:
arr = np.array([[[1,2,3],[2,3,4],[9,6,7]],[[4,5,6],[7,8,9],[9,6,7]],[[8,6,7],[6,5,9],[3,2,8]]])

In [39]:
print(arr.shape)

(3, 3, 3)


In [40]:
arr_1 = np.array([1,2,3,4,5,6,7,8], ndmin=3)
print(arr_1)
print(arr_1.shape)
print(arr_1.ndim)
print(arr_1[:,:,3])

[[[1 2 3 4 5 6 7 8]]]
(1, 1, 8)
3
[[4]]


In [41]:
arr_2 = arr_1.reshape(2,2,2)
print(arr_2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
arr_2.shape

(2, 2, 2)

In [43]:
arr_2.ndim

3

In [44]:
arr_3 = arr_2.reshape(-1,2)
print(arr_3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
arr_3.ndim

2

In [69]:
print(np.array([1,2,3,4,5,6,7,8,9,10]))

[ 1  2  3  4  5  6  7  8  9 10]


In [70]:
ar = np.array(range(1,101))
ar

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [72]:
ar2 = ar.reshape(5,5,4)
print(ar2)

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]]

 [[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]
  [ 33  34  35  36]
  [ 37  38  39  40]]

 [[ 41  42  43  44]
  [ 45  46  47  48]
  [ 49  50  51  52]
  [ 53  54  55  56]
  [ 57  58  59  60]]

 [[ 61  62  63  64]
  [ 65  66  67  68]
  [ 69  70  71  72]
  [ 73  74  75  76]
  [ 77  78  79  80]]

 [[ 81  82  83  84]
  [ 85  86  87  88]
  [ 89  90  91  92]
  [ 93  94  95  96]
  [ 97  98  99 100]]]


In [73]:
ar.ndim

1

In [102]:
for i in ar:
    if i%2==0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [103]:
ar2

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [104]:
# Picking even numbers from 3d array ar2

In [105]:
ar2[0:, 0:, 1:100:2]

array([[[  2,   4],
        [  6,   8],
        [ 10,  12],
        [ 14,  16],
        [ 18,  20]],

       [[ 22,  24],
        [ 26,  28],
        [ 30,  32],
        [ 34,  36],
        [ 38,  40]],

       [[ 42,  44],
        [ 46,  48],
        [ 50,  52],
        [ 54,  56],
        [ 58,  60]],

       [[ 62,  64],
        [ 66,  68],
        [ 70,  72],
        [ 74,  76],
        [ 78,  80]],

       [[ 82,  84],
        [ 86,  88],
        [ 90,  92],
        [ 94,  96],
        [ 98, 100]]])

In [106]:
# Picking odd numbers from 3d array ar2

In [107]:
ar2[0:, 0:, 0:100:2]

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]],

       [[21, 23],
        [25, 27],
        [29, 31],
        [33, 35],
        [37, 39]],

       [[41, 43],
        [45, 47],
        [49, 51],
        [53, 55],
        [57, 59]],

       [[61, 63],
        [65, 67],
        [69, 71],
        [73, 75],
        [77, 79]],

       [[81, 83],
        [85, 87],
        [89, 91],
        [93, 95],
        [97, 99]]])

In [108]:
for x in ar2:
    print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]
[[41 42 43 44]
 [45 46 47 48]
 [49 50 51 52]
 [53 54 55 56]
 [57 58 59 60]]
[[61 62 63 64]
 [65 66 67 68]
 [69 70 71 72]
 [73 74 75 76]
 [77 78 79 80]]
[[ 81  82  83  84]
 [ 85  86  87  88]
 [ 89  90  91  92]
 [ 93  94  95  96]
 [ 97  98  99 100]]


In [114]:
for x in ar2:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [115]:
for x in np.nditer(ar2):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [117]:
aray = np.array(range(1,101))
aray

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [120]:
for i in np.nditer(aray):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [130]:
for i in np.nditer(aray[::2]):
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


In [132]:
for id,x in np.ndenumerate(ar2):
    print(id,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 2, 0) 9
(0, 2, 1) 10
(0, 2, 2) 11
(0, 2, 3) 12
(0, 3, 0) 13
(0, 3, 1) 14
(0, 3, 2) 15
(0, 3, 3) 16
(0, 4, 0) 17
(0, 4, 1) 18
(0, 4, 2) 19
(0, 4, 3) 20
(1, 0, 0) 21
(1, 0, 1) 22
(1, 0, 2) 23
(1, 0, 3) 24
(1, 1, 0) 25
(1, 1, 1) 26
(1, 1, 2) 27
(1, 1, 3) 28
(1, 2, 0) 29
(1, 2, 1) 30
(1, 2, 2) 31
(1, 2, 3) 32
(1, 3, 0) 33
(1, 3, 1) 34
(1, 3, 2) 35
(1, 3, 3) 36
(1, 4, 0) 37
(1, 4, 1) 38
(1, 4, 2) 39
(1, 4, 3) 40
(2, 0, 0) 41
(2, 0, 1) 42
(2, 0, 2) 43
(2, 0, 3) 44
(2, 1, 0) 45
(2, 1, 1) 46
(2, 1, 2) 47
(2, 1, 3) 48
(2, 2, 0) 49
(2, 2, 1) 50
(2, 2, 2) 51
(2, 2, 3) 52
(2, 3, 0) 53
(2, 3, 1) 54
(2, 3, 2) 55
(2, 3, 3) 56
(2, 4, 0) 57
(2, 4, 1) 58
(2, 4, 2) 59
(2, 4, 3) 60
(3, 0, 0) 61
(3, 0, 1) 62
(3, 0, 2) 63
(3, 0, 3) 64
(3, 1, 0) 65
(3, 1, 1) 66
(3, 1, 2) 67
(3, 1, 3) 68
(3, 2, 0) 69
(3, 2, 1) 70
(3, 2, 2) 71
(3, 2, 3) 72
(3, 3, 0) 73
(3, 3, 1) 74
(3, 3, 2) 75
(3, 3, 3) 76
(3, 4, 0) 77
(3, 4, 1

In [135]:
ar3 = np.array(range(1,101), ndmin=3)
ar3

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
          25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
          37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
          49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
          61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
          73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
          85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100]]])

In [151]:
for id,x in np.ndenumerate(ar3):
    print(id,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 0, 5) 6
(0, 0, 6) 7
(0, 0, 7) 8
(0, 0, 8) 9
(0, 0, 9) 10
(0, 0, 10) 11
(0, 0, 11) 12
(0, 0, 12) 13
(0, 0, 13) 14
(0, 0, 14) 15
(0, 0, 15) 16
(0, 0, 16) 17
(0, 0, 17) 18
(0, 0, 18) 19
(0, 0, 19) 20
(0, 0, 20) 21
(0, 0, 21) 22
(0, 0, 22) 23
(0, 0, 23) 24
(0, 0, 24) 25
(0, 0, 25) 26
(0, 0, 26) 27
(0, 0, 27) 28
(0, 0, 28) 29
(0, 0, 29) 30
(0, 0, 30) 31
(0, 0, 31) 32
(0, 0, 32) 33
(0, 0, 33) 34
(0, 0, 34) 35
(0, 0, 35) 36
(0, 0, 36) 37
(0, 0, 37) 38
(0, 0, 38) 39
(0, 0, 39) 40
(0, 0, 40) 41
(0, 0, 41) 42
(0, 0, 42) 43
(0, 0, 43) 44
(0, 0, 44) 45
(0, 0, 45) 46
(0, 0, 46) 47
(0, 0, 47) 48
(0, 0, 48) 49
(0, 0, 49) 50
(0, 0, 50) 51
(0, 0, 51) 52
(0, 0, 52) 53
(0, 0, 53) 54
(0, 0, 54) 55
(0, 0, 55) 56
(0, 0, 56) 57
(0, 0, 57) 58
(0, 0, 58) 59
(0, 0, 59) 60
(0, 0, 60) 61
(0, 0, 61) 62
(0, 0, 62) 63
(0, 0, 63) 64
(0, 0, 64) 65
(0, 0, 65) 66
(0, 0, 66) 67
(0, 0, 67) 68
(0, 0, 68) 69
(0, 0, 69) 70
(0, 0, 70) 71
(0, 0, 71) 72
(0, 0, 72) 

In [152]:
# Single dimension
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
con = np.concatenate((a,b))
print(con)

[1 2 3 4 2 3 4 5]


In [164]:
# Two dimension
c = np.array([[1,2],[3,4]])

d = np.array([[2,3],[4,5]])

con2 = np.concatenate((a,b))

print(con2)

[1 2 3 4 2 3 4 5]


In [160]:
i = np.stack((c,d))
print(i)

[[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]]


In [161]:
j = np.hstack((c,d))
print(j)

[[1 2 2 3]
 [3 4 4 5]]


In [171]:
k = np.array([range(8)])
print(k)

[[0 1 2 3 4 5 6 7]]
