In [1]:
# One dimensional array

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# Three dimensional array

In [6]:
arr_1 = np.array([[[1,2,3],[6,8,9]],[[2,6,8],[9,6,8]],[[4,6,8],[2,9,6]]])
print(arr_1)

[[[1 2 3]
  [6 8 9]]

 [[2 6 8]
  [9 6 8]]

 [[4 6 8]
  [2 9 6]]]


In [7]:
np.__version__

'1.19.2'

In [8]:
arr_1.ndim

3

In [9]:
arr_1.ndim

3

In [10]:
arr_2 = np.array([1,2,3,4])
print(arr_2[:2])

[1 2]


In [11]:
arr_2[3] = arr_2[1] + arr_2[2]
print(arr_2[3])

5


In [12]:
print(len(arr_2))

4


In [13]:
print(len(arr_1))

3


In [14]:
arr_3 = np.array([[1,2,3,4],[3,5,6,4]])
print(arr_3[0,1])

2


In [15]:
arr_4 = np.array([[[1,2,3],[6,8,9]],[[2,6,8],[9,6,8]],[[4,6,8],[2,9,6]]])
print(arr_4[-1][-1][-1])
print(arr_4[len(arr_4)-1])

6
[[4 6 8]
 [2 9 6]]


In [19]:
arr_4

array([[[1, 2, 3],
        [6, 8, 9]],

       [[2, 6, 8],
        [9, 6, 8]],

       [[4, 6, 8],
        [2, 9, 6]]])

In [17]:
arr_4.size

18

In [51]:
arr_4.ndim

3

In [72]:
arr_4[-1:-2:-1]

array([[[4, 6, 8],
        [2, 9, 6]]])

In [75]:
arr_4[-1:-2:-1][-1,-1]

array([2, 9, 6])

In [76]:
arr_4[-1:-2:-1][-1,-1][2]

6

In [78]:
arr_5 = np.array([[[1,2,3],[2,3,4],[9,6,7]],[[4,5,6],[7,8,9],[9,6,7]],[[8,6,7],[6,5,9],[3,2,8]]])

In [79]:
arr_5

array([[[1, 2, 3],
        [2, 3, 4],
        [9, 6, 7]],

       [[4, 5, 6],
        [7, 8, 9],
        [9, 6, 7]],

       [[8, 6, 7],
        [6, 5, 9],
        [3, 2, 8]]])

In [81]:
arr_5.ndim

3

In [82]:
arr_5.size

27

In [83]:
arr_5[-1,-2]

array([6, 5, 9])

In [93]:
arr_5[-1,-1,-1]

8